### ISSUE TITLE
Remove "Sent via" links

### ISSUE THREAD

**Issue by pigsonthewing** [edent/Dabr#114]
To further declutter the interface, and reduce instances of the wrong link being selected, please remove "Sent via" links from the main stream page( https://dabr.eu/ ).

They would still be available on the page for the /individual/ tweet (e.g. https://dabr.eu/status/717419511255801856 )

**Comment by edent** [comment]
Still thinking about this. Not sure how to decouple the "sent via" so it only appears in the one place.

**Comment by edent** [comment]
Have decided against this, for I am a capricious god.

**Comment by pigsonthewing** [comment]
Fascist.
