### ISSUE TITLE
Included file "hides" rest of page

### ISSUE THREAD

**Issue by pigsonthewing** [edent/Dabr#124]
A search for "balloon release" currently finds the tweet https://dabr.eu/status/739771629241171968 as the first result of many.

As the page loads, the following tweets are visible, but one the included file has loaded and is displayed, everything below it (subsequent tweets, page footer chrome, etc) is missing.

**Comment by edent** [comment]
Think this is caused by #67 - will look into it.

**Comment by pigsonthewing** [comment]
Yes; it's a Google+ embed. Thanks.
