### ISSUE TITLE
Cannot mention users who block me in DMs

### ISSUE THREAD

**Issue by pigsonthewing** [edent/Dabr#127]
A tweet containing, for example, the text:

> D @Dabr That @NadineDorriesMP has blocked me!

or:

> D Dabr That @NadineDorriesMP has blocked me!

cannot be sent by someone who has indeed been blocked by that account.

(The text:

> That @NadineDorriesMP has blocked me!

can be sent using https://dabr.eu/messages/create )

**Comment by edent** [comment]
This is by design.

**Comment by pigsonthewing** [comment]
Why?

**Comment by edent** [comment]
It makes it slightly harder for people to encourage pile-ons.
