### ISSUE TITLE
Twitter polls do not render

### ISSUE THREAD

**Issue by pigsonthewing** [edent/Dabr#144]
Tweets like:

https://twitter.com/StephenAtHome/status/690702013567504384

![poll](https://user-images.githubusercontent.com/89541/34325572-2aad83d6-e88d-11e7-8348-d95c87631a3d.jpg)

which include a poll, do not render the poll:

https://dabr.eu/status/690702013567504384

![poll](https://user-images.githubusercontent.com/89541/34325563-ec99a96c-e88c-11e7-9e37-96e6989910b0.jpg)

If it is not possible to do so, a placeholder text such as "View tweet on Twitter to view poll", including a link, should be displayed.

**Comment by edent** [comment]
There is no API support for polls. We don't even get an indication that there is a poll on a tweet.

https://twittercommunity.com/t/poll-support/78235


😥😒😫😢😤😖
