### ISSUE TITLE
Tweet ID error on local install

### ISSUE THREAD

**Issue by degsyh** [edent/Dabr#48]
Hello, I've installed new dabr on my local webserver. Everything seems to be ok apart from the tweet ID's seem to be coming back as numbers which overflow. ie /dabr/status/5.6956254349418E+17 

I therefore cant click through the timestamp or view retweeted_by links. I'm guessing its because they should be being brought back as strings rather than numerical but cant work out where to change in the code. I notice the 32bit/ snowflake stuff has been commented out but reinstating it doesnt seem to work as it looks like the twitter_process calls have been replaced by the codebird functions? Any idea what I should do? 

Thanks in advance. Derek

**Comment by edent** [comment]
Hi @degsyh - do you know which version of PHP you're running?

**Comment by degsyh** [comment]
Hi @edent its a windows x64 version of 5.6.6 i tried switching to x86 but still no joy. I noticed that the ID's are correct in "in reply to" links..

**Comment by edent** [comment]
Can you please tell me what your `PHP_INT_SIZE` and `PHP_INT_MAX ` are?

Wonder if it's something to do with http://php.net/manual/en/language.types.integer.php

**Comment by degsyh** [comment]
The values are as follows:
PHP_INT_SIZE: 4
PHP_INT_MAX: 2,147,483,647

looks like these are set at php compile time?

I've got round it in the end by replacing all instances of status->id with status->id_str

Thanks for investigating :)

**Comment by edent** [comment]
@degsyh can you submit it as a patch, please :-)

**Comment by degsyh** [comment]
Amended the snowflake patch in the end. Patch submitted - hope i've done it right new to Github. :-)
