### ISSUE TITLE
Provide a "view in Dabr" link for directly-linked tweets

### ISSUE THREAD

**Issue by pigsonthewing** [edent/Dabr#62]
Changes to Twitter mean that tweets like:

https://twitter.com/IBIS_journal/status/618455585672069120

whose content:

   #ornithology http://twitter.com/Natures_Voice/status/618418140876247041  

includes the URL of a tweet at twitter.com, are increasingly prevalent.

I understand that Twitter's ToCs prohibit these from being rewritten, but a footnote ("view linked tweet in Dabr") would be useful. It could perhaps go between the existing "View original tweet on Twitter" and "Translate this tweet" links, in the view for an individual tweet.

**Comment by edent** [comment]
If you go to dabr.eu/settings and tick the "Show link previews (YouTube, Instagram, Blogs, etc)." option, you will get a rich preview of the Tweet.

Currently the tweets aren't exposed in the metadata, so requesting them could drive a user over their limit.

**Comment by pigsonthewing** [comment]
Thanks; but I don't want previews for YouTube or Instagram.

**Comment by edent** [comment]
I'll see if there's a sensible way to view only that tweet.
