### ISSUE TITLE
Change location search to use OpenStreetMap

### ISSUE THREAD

**Issue by pigsonthewing** [edent/Dabr#68]
Please change Dabr's location links to search OpenStreetMap instead of Google (because open).

[You could test for the presence for coordinates, rather than a place name, and if found link directly instead of searching.]

If that's not acceptable, please provide a user-setting to choose which mapping service to use.

**Comment by edent** [comment]
OSM map with marker is http://www.openstreetmap.org/?mlat=51.7&mlon=-1.23#map=15/51.7/-1.23

Checking to see how mobile friendly it is and if it can cope with names ("Hong Kong", "London", "My Bedroom" are all common strings.)

**Comment by edent** [comment]
Hmmm.... Can use http://wiki.openstreetmap.org/wiki/Nominatim

* https://nominatim.openstreetmap.org/search?q=34.63677866,135.22868514
* https://nominatim.openstreetmap.org/search?q=Hong%20Kong

No way to add marker or zoom level though?

**Comment by edent** [comment]
But nominatim is *not* mobile friendly... The regular OSM is.

**Comment by edent** [comment]
Open MapQuest is based on OSM.

* http://open.mapquest.co.uk/?q=oxford,uk
* http://open.mapquest.co.uk/?q=34.63677866,135.22868514

Not mobile friendly :-(

**Comment by edent** [comment]
On hold pending an answer at https://help.openstreetmap.org/questions/46452/mobile-link-to-first-search-result-is-this-possible

**Comment by edent** [comment]
This is not possible at this time.  There are no OSM based sites which will take a location string and return a mobile friendly page.

Happy to re-open if that changes.
